module.exports = {
  CREATE_PERMISISON: 'create-permission',
  UPDATE_PERMISISON: 'update-permission',
  DELETE_PERMISISON: 'delete-permission',
  READ_PERMISISON: 'read-permission',
  CREATE_ROL: 'create-rol',
  UPDATE_ROL: 'update-rol',
  DELETE_ROL: 'delete-rol',
  READ_ROL: 'read-rol',
  LIST_PERMISSION_PARANOID: 'list-permission-paranoid',
  RESTORE_PERMISSION_PARANOID: 'restore-permission-paranoid',
  CREATE_CATEGORY_OF_PRODUCT: 'create-category-of-product',
  UPDATE_CATEGORY_OF_PRODUCT: 'update-category-of-product',
  DELETE_CATEGORY_OF_PRODUCT: 'delete-category-of-product',
  READ_CATEGORY_OF_PRODUCT: 'read-category-of-product',
  CREATE_PRODUCT_OF_FOOD: 'create-product-of-food',
  UPDATE_PRODUCT_OF_FOOD: 'update-product-of-food',
  DELETE_PRODUCT_OF_FOOD: 'delete-product-of-food',
  READ_PRODUCT_OF_FOOD: 'read-product-of-food',
  CREATE_USER: 'create-user',
  UPDATE_USER: 'update-user',
  DELETE_USER: 'delete-user',
  READ_USER: 'read-user'
};
